import { defineConfig } from 'oxlint'

export default defineConfig({
  categories: {
    correctness: 'error',
    nursery: 'warn',
    pedantic: 'warn',
    perf: 'warn',
    restriction: 'error',
    style: 'warn',
    suspicious: 'error',
  },
  env: {
    builtin: true,
    node: true,
  },
  ignorePatterns: ['dist', 'node_modules', 'src-tauri', '**/*.js'],
  jsPlugins: [
    {
      name: 'vite-plus',
      specifier: 'vite-plus/oxlint-plugin',
    },
  ],
  options: {
    reportUnusedDisableDirectives: 'error',
    typeAware: true,
    typeCheck: true,
  },
  overrides: [
    {
      files: ['ecosystem.config.cjs'],
      env: {
        node: true,
      },
      rules: {
        'import/no-commonjs': 'off',
        'import/unambiguous': 'off',
      },
    },
  ],
  plugins: [
    'import',
    'promise',
    'node',
    'eslint',
    'typescript',
    'unicorn',
    'oxc',
  ],
  rules: {
    'eslint/max-lines-per-function': ['warn', { max: 500 }],
    'eslint/max-lines': ['warn', { max: 500 }],
    'import/max-dependencies': ['warn', { max: 30 }],
    'max-statements': ['warn', { max: 30 }],
    'capitalized-comments': 'off',
    'eslint/id-length': 'off',
    'eslint/no-ternary': 'off',
    'eslint/no-void': 'off',
    'eslint/sort-imports': 'off',
    'eslint/sort-keys': 'off',
    'import/consistent-type-specifier-style': [
      'error',
      'prefer-top-level-if-only-type-imports',
    ],
    'import/group-exports': 'off',
    'import/no-default-export': 'off',
    'import/no-named-export': 'off',
    'import/no-relative-parent-imports': 'off',
    'one-var': 'off',
    'oxc/no-async-await': 'off',
    'oxc/no-optional-chaining': 'off',
    'oxc/no-rest-spread-properties': 'off',
    'typescript/explicit-function-return-type': 'off',
    'typescript/explicit-module-boundary-types': 'off',
    'typescript/prefer-readonly-parameter-types': 'off',
    'typescript/promise-function-async': 'off',
    'unicorn/filename-case': [
      'error',
      {
        cases: {
          camelCase: true,
          pascalCase: true,
        },
      },
    ],
    'vite-plus/prefer-vite-plus-imports': 'error',
    'unicorn/no-null': 'off',
    'eslint/no-undefined': 'off',
    'eslint/no-nested-ternary': 'off',
    'unicorn/explicit-length-check': 'off',
    'no-magic-numbers': 'off',
    'import/prefer-default-export': 'off',
    'eslint/init-declarations': 'off',
    'typescript/strict-boolean-expressions': 'off',
    'eslint/new-cap': 'off',
    'eslint/no-console': 'warn',
    'import/no-named-as-default-member': 'off',
    'import/no-nodejs-modules': 'off',
    'oxc/no-async-endpoint-handlers': 'off',
    'node/no-top-level-await': 'off',
    'eslint/no-continue': 'off',
    'typescript/no-confusing-void-expression': 'off',
    'typescript/consistent-return': 'off',
    'import/no-cycle': 'off',
    'typescript/explicit-member-accessibility': 'off',
    'eslint/max-params': 'off',
  },
})
